[package]
name = "wtt"
version = "1.0.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.41", features = ["derive"] }
cli-table = "0.5.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
uuid = { version = "1.18.0", features = ["v4"] }
